name: Sandbox Pipeline

on:
  pull_request_review:
    types:
      - submitted
    branches-ignore:
      - master

jobs:
  Plan:
    name: "Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: echo "Rodar somente o plano Sandbox > tf-cicd-stg-review.yml"

  Apply:
    if: github.event.review.state == 'approved'
    name: "Apply"
    runs-on: ubuntu-latest
    needs: [Plan]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: echo "Rodar somente o APPLY apÃ³s approved em Sandbox > tf-cicd-stg-review.yml"
